### ISSUE TITLE
【BUG】执行删除爬虫操作的时候，未一并删除相关联的定时任务，导致定时任务页面报错

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab-lite#11]
**Bug 描述**
例如，当 执行删除爬虫操作 时，未一并删除相关联的定时任务吗，导致定时任务管理 功能不工作。

**复现步骤**
该 Bug 复现步骤如下
1. 上传 N 个爬虫
2. 创建几个相关的定时任务
3. 删除其中一个爬虫
4. 定时任务页面报错 “spider not found”，并且不展示定时任务

**期望结果**
定时任务 管理 能工作。

**截屏**
木有

**Comment by zkqiang** [comment]
master 分支已修改，欢迎测试
