### ISSUE TITLE
请问如何添加多个用户？

### ISSUE THREAD

**Issue by zhlid** [crawlab-team/crawlab-lite#12]
在使用的过程中，爬虫有误删的情况，想增加普通用户，让其不能删除爬虫

**Comment by zkqiang** [comment]
Lite 版设计之处就不考虑加入权限功能，不然这个功能做起来需求会源源不断，就变的臃肿了

误删的问题，后续可以考虑通过 "提示勾选框" 或者 "输入密码" 的二次确认方式来减少误删

**Comment by zkqiang** [comment]
master 分支加入了删除二次确认
