### ISSUE TITLE
【增强】优化磁盘 IO 占用

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab-lite#14]
**请描述该需求尝试解决的问题**
当 日志列表存在大量日志(大概存在 250条 左右的日志) 时，程序读写硬盘将达到 3MB/s
清空日志列表后，读写 IO 将显著下降到 0.5MB/s

是否是因为程序一直在遍历 kvdb 或磁盘以便清理过期日志及文件造成的？
（注：只有5个低频的定时任务，执行间隔半个小时/一个小时不等的那种，另外一天只有16小时左右的调度区间）

**请描述您认为可行的解决方案**
优化程序的磁盘 IO 占用

2020/09/27 更新：
增加贴图
![0FtyRS.png](https://s1.ax1x.com/2020/09/27/0FtyRS.png)

图片说明，9月8号之前是没有使用 docker 部署 crawlab-lite 的，部署之后读写流量飙升
为啥能用网络流量仪监控到，是因为我用的网络存储SSD持久化的数据文件
中间有几天下载数据量超过20GB的是因为那几天在测试 InfluxDB 数据库，所以那几天可以忽略
但是再扣掉9月8号之前的基础读写量，crawlab-lite 的读写量还是异常惊人，这样的话 SSD 估计很快就能写废

**考虑过的替代方案**
无

**Comment by zkqiang** [comment]
ok，准备改成数据库存储了

**Comment by zkqiang** [comment]
master 分支已修改，欢迎测试

**Comment by Zerorigin** [comment]
> master 分支已修改，欢迎测试

计划任务需要手动迁移？

**Comment by zkqiang** [comment]
> 计划任务需要手动迁移？

旧的日志会丢失，其他不受影响

**Comment by Zerorigin** [comment]
> master 分支已修改，欢迎测试

磁盘读写 IO 并无明显改观
这是10月5号，从 master 分支利用 Dockerfile 重新构建的镜像测试结果截图
![0Bcq5F.png](https://s1.ax1x.com/2020/10/09/0Bcq5F.png)

**Comment by zkqiang** [comment]
那是不是日志确实有那么多，因为我看上传一直居高不下，上传流量应该跟实现逻辑的关系不大

另外如果从 SSD 寿命考虑，不需要关注流量，我可以加入一些降低读写频次的手段

**Comment by Zerorigin** [comment]
> 那是不是日志确实有那么多，因为我看上传一直居高不下，上传流量应该跟实现逻辑的关系不大
> 另外如果从 SSD 寿命考虑，不需要关注流量，我可以加入一些降低读写频次的手段

日志大概就200条左右，并不是非常多
上传流量比较无所谓，下载流量是写到 SSD 上的
另外这是资源监视器的磁盘IO截图
![0DknaR.png](https://s1.ax1x.com/2020/10/09/0DknaR.png)

**Comment by zkqiang** [comment]
回头我再针对测试一下
