### ISSUE TITLE
v0.0.4 服务宕机

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab-lite#17]
**Bug 描述**
version: v0.0.4

该版本容器部署的服务会宕机

**Comment by zkqiang** [comment]
请贴具体报错... 不然怎么看出问题

我部署是可以的

**Comment by Zerorigin** [comment]
> 请贴具体报错... 不然怎么看出问题
> 
> 我部署是可以的

docker-compose logs:
https://paste.ubuntu.com/p/sBWwrbqRtV/
