### ISSUE TITLE
运行 后端项目报错

### ISSUE THREAD

**Issue by zhangyupy** [crawlab-team/crawlab-lite#18]
**Bug 描述**
go: github.com/ahmetb/go-linq@v3.0.0+incompatible: Get "https://proxy.golang.org/github.com/ahmetb/go-linq/@v/v3.0.0+incompatible.mod": dial tcp 34.64.4.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by zkqiang** [comment]
下载包的时候网络问题...
