### ISSUE TITLE
执行gocolly的爬虫时，提示missing $GOPATH

### ISSUE THREAD

**Issue by cinos1** [crawlab-team/crawlab-lite#22]
**Bug 描述**
执行gocolly的爬虫时，提示missing $GOPATH

**复现步骤**
该 Bug 复现步骤如下
1. 直接按照帮助使用docker-compose up -d 启动项目
2. 更新dokcer文件内容，增加go环境
3. 通过docker exec -it 进入docker，执行go run xxxx.go可正常执行
4. 通过前端页面上传zip包提示missing $GOPATH

**期望结果**
请问是我的docker go环境增加有问题么？正确的增加go环境是如何操作，谢谢！

**截屏**

**Comment by zkqiang** [comment]
拉最新镜像试一下？
