### ISSUE TITLE
请问怎么把8080端口修改成其他端口呢

### ISSUE THREAD

**Issue by shilin414** [crawlab-team/crawlab-lite#23]
作者您好，叨扰您，请问怎么把8080端口修改成其他端口呢？我尝试讲ngix和docker-compose.yml还有docker-init文件里的涉及到8080端口的地方修改掉，但是仍然还是能从8080端口访问，想知道应该修改哪里

**Comment by zkqiang** [comment]
修改 docker-compose.yml：
```yaml
    ports:
      - "8080:1234"
```

这个是端口映射，两个端口分别是 HOST_PORT 和 CONTAINER_PORT，HOST_PORT 在不修改前端配置的情况下不需要修改

具体可见 ： https://docs.docker.com/compose/networking/

**Comment by shilin414** [comment]
您好 ，我刚才试了一下，把 HOST_PORT 改了就好了，改成5050：8080，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crawlab-team/crawlab-lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crawlab-team/crawlab-lite] 请问怎么把8080端口修改成其他端口呢 (#23)





 
修改 docker-compose.yml：
     ports:       - "8080:1234"
 
这个是端口映射，两个端口分别是 HOST_PORT 和 CONTAINER_PORT，HOST_PORT 在不修改前端配置的情况下不需要修改
