### ISSUE TITLE
定时任务栏查看任务存在无法查看的bug

### ISSUE THREAD

**Issue by Oborozukiyo** [crawlab-team/crawlab-lite#24]
**Bug 描述**
使用docker部署完后，添加爬虫项目，然后在**定时任务**添加一个任务，
当任务执行结束，在**任务**栏可以见到任务状态，
但是在**定时任务**栏点击相应任务的**查看任务**按钮，看不到相应记录，返回结果为空。

我自己多次安装测试，发现在添加一个定时任务之后，
需要重新启动容器，之后该定时任务所运行的任务才能在定时任务栏里查看到。
每添加新的定时任务，都需要重启容器

此外还有一个小bug，定义完一个定时任务后，点击编辑按钮，再点击编辑cron表达式，读取的时间信息会出现错位，比如“0 0 15 * * *”在点击编辑按钮之后，如果什么都不改就保存，cron表达式最后会变成“0 0 0 15 * *”

**Comment by zkqiang** [comment]
master 已修复两个问题
