### ISSUE TITLE
用crawlab-go-sdk抓取数据生成爬虫抓取失败

### ISSUE THREAD

**Issue by flazx** [crawlab-team/crawlab-lite#25]
**Bug 描述**
根据https://github.com/crawlab-team/crawlab-go-sdk的相关描述，生成一个爬虫，把采集的数据存入kv的lite数据，结果出错。从错误信息看是保存采集数据的问题。那我的问题是如何采集数据到kvdb呢？

** SDK 错误信息  **
12021/05/18 23:29:06 $1 dial mongo error: no reachable servers
2goroutine 1 [running]:
3runtime/debug.Stack(0x0, 0x0, 0x0)
4/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
5runtime/debug.PrintStack()
6/usr/local/go/src/runtime/debug/stack.go:16 +0x25
7github.com/crawlab-team/crawlab-go-sdk/database.GetDataSourceCol(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
8/home/ricky/go/pkg/mod/github.com/crawlab-team/crawlab-go-sdk@v0.0.6/database/mongo.go:39 +0x4e7
9github.com/crawlab-team/crawlab-go-sdk/database.GetMongoCol(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
10/home/ricky/go/pkg/mod/github.com/crawlab-team/crawlab-go-sdk@v0.0.6/database/mongo.go:50 +0x23f
11github.com/crawlab-team/crawlab-go-sdk/utils.SaveItemMongo(0xc000113830, 0x0, 0x0)
12/home/ricky/go/pkg/mod/github.com/crawlab-team/crawlab-go-sdk@v0.0.6/utils/data.go:37 +0x78
13github.com/crawlab-team/crawlab-go-sdk/utils.SaveItem(0xc000113830, 0xc000113830, 0x879ec0)
14/home/ricky/go/pkg/mod/github.com/crawlab-team/crawlab-go-sdk@v0.0.6/utils/data.go:16 +0x1d7
15github.com/crawlab-team/crawlab-go-sdk.SaveItem(...)
16/home/ricky/go/pkg/mod/github.com/crawlab-team/crawlab-go-sdk@v0.0.6/main.go:9
17main.main()
18/home/ricky/lab/golang/hello/spiders/main.go:12 +0xe5

**Comment by zkqiang** [comment]
crawlab-lite 是不支持 crawlab-sdk 的
