### ISSUE TITLE
go run main.go error

### ISSUE THREAD

**Issue by wolf-leo** [crawlab-team/crawlab-lite#3]
# crawlab-lite/managers
managers\execute.go:234:42: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr
managers\task.go:97:10: undefined: syscall.Kill

**Comment by zkqiang** [comment]
golang 版本是多少？  操作系统是什么？

**Comment by wolf-leo** [comment]
windows 10 64
go version go1.14.3 windows/amd64

**Comment by zkqiang** [comment]
那有点奇怪，windows应该不会走到报错的那行代码

可能是 1.14 版本有些变化

方便的话，可以在 managers\execute.go:233 行，把 `runtime.GOOS` 的值打印出来看下

**Comment by charmer21** [comment]
我也遇到同样的问题

**Comment by zkqiang** [comment]
@charmer21 麻烦按我上面说的打印出来看看？

**Comment by Shimon-Cheung** [comment]
打印不出来得，直接编译检查就崩了，我试了想去打印runtime.GOOS

**Comment by Shimon-Cheung** [comment]
![image](https://user-images.githubusercontent.com/38549441/93306248-2de11380-f832-11ea-9235-b49577297d7c.png)
![image](https://user-images.githubusercontent.com/38549441/93306269-33d6f480-f832-11ea-8cbc-a60331bfa93b.png)

**Comment by Shimon-Cheung** [comment]
我试了1.15和1.2.17都报这个错误，可能是windows得原因，作者可以使用windows试试看，就能复现这个错误了

**Comment by zkqiang** [comment]
master 分支已修复
