### ISSUE TITLE
请问这个数据库 是什么数据库，怎么可视化数据库 .db的内容

### ISSUE THREAD

**Issue by Lu-dashuai** [crawlab-team/crawlab-lite#31]
**请描述该需求尝试解决的问题**
例如，当 xxx 时，我总是被当前 xxx 的设计所困扰。

**请描述您认为可行的解决方案**
例如，添加 xxx 功能能够解决问题。

**考虑过的替代方案**
例如，如果用 xxx，也能解决该问题。

**Comment by zkqiang** [comment]
boltDB  文件型KV数据库

在 `volumes` 挂载目录下能找到 DB 文件
