### ISSUE TITLE
【BUG】通过 config.yml 配置文件自定义密码无效

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab-lite#6]
# 额，好吧，好像看到了这个 https://github.com/crawlab-team/crawlab-lite/issues/5
建议完善下 crawlab-lite 的相关文档

**Bug 描述**
Version: 0.0.2
例如，当 使用 docker 部署 时，通过 config.yml 配置文件自定义密码 功能不工作。

**复现步骤**
该 Bug 复现步骤如下
1.  将 /app/backen/config.yml 配置文件映射出来，并自定义好密码
2.  docker run 或 docker-compose up -d 运行 crawlab-lite
3.  打开 crawlab-lite web，尝试用自定义密码登录，提示密码错误，但可用默认密码登录

**期望结果**
自定义密码 能工作。

**截屏**
无

**Comment by zkqiang** [comment]
docker 部署设置这个：
https://github.com/crawlab-team/crawlab-lite/blob/2677de9e1aa97284ee68385d58c022de53b0428c/docker-compose.yml#L12
