### ISSUE TITLE
【BUG】过期的任务未隧日志文件一并删除

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab-lite#7]
**Bug 描述**
Version: 0.0.2
例如，当 使用 docker 部署 时，通过 config.yml 配置文件自定义日志过期 功能不完全正常。

**复现步骤**
该 Bug 复现步骤如下
1. 将 /app/backen/config.yml 配置文件映射出来，并自定义好 log.expireDays
2. docker run 或 docker-compose up -d 运行 crawlab-lite
3. 运行一段时间的定时任务
4. 可以正常删除过期的日志文件，但空日志的定时任务还是残留在任务选项卡界面

**期望结果**
 任务过期功能 能正常工作。

**截屏**
无

**Comment by zkqiang** [comment]
master 分支添加了定期删除任务功能

日志和任务的过期这里进行了分开处理，原因是任务并不只有日志，还包含了一些运行数据（虽然目前这些数据比较少）

**Comment by arden-yang** [comment]
任务运行时一直卡在更新日志这里
