### ISSUE TITLE
【增强】任务管理增加批量删除任务日志功能

### ISSUE THREAD

**Issue by Zerorigin** [crawlab-team/crawlab-lite#8]
**请描述该需求尝试解决的问题**
Version: 0.0.2
例如，当 删除任务 时，我总是被当前 只能 一个一个删除旧的任务日志 的设计所困扰，因为这样太没有效率了。

**请描述您认为可行的解决方案**
例如，添加 批量删除任务日志 功能能够解决问题。

**考虑过的替代方案**
例如，如果用 抓包调用 HTTP API，也能暂时解决该问题，但是需要编写一份脚本。

**截屏**
![dMxPsg.png](https://s1.ax1x.com/2020/08/19/dMxPsg.png)

**Comment by zkqiang** [comment]
批量操作下个版本会集中加入
